// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlk3b7fSUsB2h7pMa7CwDOl0AOS8s52k',
    appId: '1:1073939648622:android:12f9c65dba359eda40567f',
    messagingSenderId: '1073939648622',
    projectId: 'foodbridge-48642',
    storageBucket: 'foodbridge-48642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd04VBWNdwoREHLeEDasPh0QqJSd6zb8I',
    appId: '1:1073939648622:ios:374da872e657a4be40567f',
    messagingSenderId: '1073939648622',
    projectId: 'foodbridge-48642',
    storageBucket: 'foodbridge-48642.firebasestorage.app',
    iosBundleId: 'com.example.foodbridge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDkiZ0HcJRLewbfhQlJOe6kkyPFBLmyZI',
    appId: '1:1073939648622:web:a500ff53f6b23ae040567f',
    messagingSenderId: '1073939648622',
    projectId: 'foodbridge-48642',
    authDomain: 'foodbridge-48642.firebaseapp.com',
    storageBucket: 'foodbridge-48642.firebasestorage.app',
    measurementId: 'G-91B24E544L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd04VBWNdwoREHLeEDasPh0QqJSd6zb8I',
    appId: '1:1073939648622:ios:374da872e657a4be40567f',
    messagingSenderId: '1073939648622',
    projectId: 'foodbridge-48642',
    storageBucket: 'foodbridge-48642.firebasestorage.app',
    iosBundleId: 'com.example.foodbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDkiZ0HcJRLewbfhQlJOe6kkyPFBLmyZI',
    appId: '1:1073939648622:web:df162ab6fa07b6fe40567f',
    messagingSenderId: '1073939648622',
    projectId: 'foodbridge-48642',
    authDomain: 'foodbridge-48642.firebaseapp.com',
    storageBucket: 'foodbridge-48642.firebasestorage.app',
    measurementId: 'G-SX1ZTSC6JZ',
  );

}